name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]  # or any branch you prefer

permissions:
  contents: read
  packages: write  # <--- Add this line to allow pushing to GHCR
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) (Optional) Setup .NET if you want to run dotnet commands
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      # 3) Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # GitHub automatically provides GITHUB_TOKEN with write package permissions (see note below).
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4) Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.actor }}/trainings:latest \
            -f AZ2003App/Dockerfile \
            

      # 5) Push to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.actor }}/trainings:latest

      - name: Azure Login
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Container Apps extension
        run: |
          az extension add --name containerapp --yes --upgrade

      - name: Update Container App
        run: |
          az containerapp update \
            --name aca-az2003 \
            --resource-group aca-dev-rg \
            --image ghcr.io/vzjackally/trainings:latest          
